name: mean_base_project
description: A Base Flutter Project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #copy after that line
  #!FOR OPERATIONS
  theme_provider:  ^0.6.0 #app's theme handling
  provider: ^6.0.5 #state management
  http: ^0.13.6

  #!USER EXPERIENCES
  animations: ^2.0.7 #handling animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
